<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-16BLF8J" failures="2" tests="3" name="Surefire test" time="3.916" errors="0" timestamp="2024-03-16T20:01:47 IST">
  <testcase classname="SeleniumJenkins.SeleniumJenkins.AppTest" name="validateLoginTC" time="1.517"/>
  <testcase classname="SeleniumJenkins.SeleniumJenkins.AppTest" name="validateLoginTC" time="1.112">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/] but found [https://www.saucedemo.com/inventory.html]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/] but found [https://www.saucedemo.com/inventory.html]
at SeleniumJenkins.SeleniumJenkins.AppTest.validateLoginTC(AppTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- validateLoginTC -->
  <testcase classname="SeleniumJenkins.SeleniumJenkins.AppTest" name="validateLoginTC" time="1.249">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/] but found [https://www.saucedemo.com/inventory.html]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/] but found [https://www.saucedemo.com/inventory.html]
at SeleniumJenkins.SeleniumJenkins.AppTest.validateLoginTC(AppTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- validateLoginTC -->
</testsuite> <!-- Surefire test -->
